Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Test.DataAccess.Base;

namespace Test.Models
{
    public class Order : IEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public DateTime CreateDate { get; set; }

        #region relationships
        public int ClientId { get; set; }
        public virtual Client Client { get; set; }
        #endregion
    }
}

ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Test.DataAccess.Base;

namespace Test.ViewModels
{
    public class OrderViewModel : IEntity
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Поле обязательно для заполнения")]
        [Display(Name = "Наименование")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Поле обязательно для заполнения")]
        [Display(Name = "Цена")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Поле обязательно для заполнения")]
        [Display(Name = "Дата заказа")]
        public DateTime CreateDate { get; set; }
        public int ClientId { get; set; }
    }
}

Controllers/ClientController.cs
using System.Web.Mvc;
using Test.Models;
using Test.Services.Implementations;
using Test.Services.Interfaces;
using Test.ViewModels;

namespace Test.Controllers
{
    // inheriting from base controller. Set Client as TEntity, ClientViewModel as TEntityViewModel
    public class ClientController : BaseController<Client, ClientViewModel>
    {
        public ClientController(
            IBaseService<Client, ClientViewModel> service // autofac resolve this as BaseService<Client, ClientViewModel> and create repository instance
            ) : base(service) // call the constructor of base service
        { }
    }

}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Test.Models;
using Test.Services.Interfaces;
using Test.ViewModels;

namespace Test.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IBaseService<Order, OrderViewModel> _service;
        public OrderController(
            IBaseService<Order, OrderViewModel> service,
            IOrderService orderService
            )
        {
            _orderService = orderService;
            _service = service;
        }

        [HttpGet]
        public virtual async Task<ActionResult> GridByReferenceId(int id, int page = 0)
        {
            if (!Request.IsAjaxRequest())
            {
                return View("Error");
            }

            var model = await _orderService.GetByReferenceIdAsync(id, page);
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> CreateOrUpdateByReferenceId(int referenceId, int? id = null)
        {
            if (!Request.IsAjaxRequest())
            {
                return View("Error");
            }

            var model = await _orderService.CreateOrUpdateByReferenceIdAsync(referenceId, id);
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateOrUpdateByReferenceId(OrderViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return View("Error");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _service.CreateOrUpdate(model);
                return RedirectToAction("GridByReferenceId", new { id = model.ClientId });
            }
            catch (Exception e)
            {
                return View("ErrorModal", e.Message);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id, int parentId)
        {
            if (!Request.IsAjaxRequest())
            {
                return View("Error");
            }

            try
            {
                await _service.Delete(id);
                return RedirectToAction("GridByReferenceId", new { id = parentId });
            }
            catch (Exception e)
            {
                return View("ErrorModal", e.Message);
            }
        }
    }
}

Views/Order/CreateOrUpdateByReferenceId.cshtml
@model Test.ViewModels.OrderViewModel

@{
    Layout = null;
}

<div id="client">
    <div class="m-2">
        @Ajax.ActionLink("<-- Вернуться к списку", "GridByReferenceId", "Order", new { id = Model.ClientId }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "modal-body" })
    </div>
    @using (Ajax.BeginForm("CreateOrUpdateByReferenceId", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "modal-body" }))
    {
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.ClientId)
            <div class="form-group">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Price)
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control format" })
                @Html.ValidationMessageFor(m => m.Price)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CreateDate)
                @Html.TextBoxFor(m => m.CreateDate, new { @class = "form-control datetime" })
                @Html.ValidationMessageFor(m => m.CreateDate)
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    }
    <script>
        // #TODO. workaround, datetimepicker and mask cleared when response contains validation errors
        initDatePicker('#client', '.datetime');
        initMaskedInput('#client', '.format');

        $('#client').on('click', '[type=submit]', (e) => {
            e.preventDefault();
            clearMask('#client', '.format');

            $(e.target).closest('form').submit();
        })
    </script>
</div>

Views/Order/GridByReferenceId.cshtml
@model Test.ViewModels.IndexViewModel<Test.Models.Order>

@{
    Layout = null;
}

<div id="orders-grid-container">
    <div class="m-2">
        <a href="@Url.Action("CreateOrUpdate", "Client", new { id = Model.ParentId })" data-type="open-modal">@("<-- Вернуться к клиенту") </a>
        
    </div>
    <div class="m-2">
        <a href="@Url.Action("CreateOrUpdateByReferenceId", "Order", new { referenceId = Model.ParentId })" class="btn btn-outline-dark btn-sm btn-block" data-type="open-modal">Добавить</a>
    </div>
    @if (Model == null || !Model.Items.Any())
    {
        <div class="alert alert-info" role="alert">
            Данные отсутствуют
        </div>
    }
    else
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Наименование</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Дата создания</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model.Items)
                {
                    <tr>
                        <th scope="col">
                            <a href="@Url.Action("Delete", null, new { id = order.Id, parentId = Model.ParentId })"
                               data-ajax="true"
                               data-ajax-method="POST"
                               data-ajax-mode="replace"
                               data-ajax-update="#orders-grid-container">
                                Удалить
                            </a>
                        </th>
                        <td scope="row"><a href="@Url.Action("CreateOrUpdateByReferenceId", new { referenceId = order.ClientId, id = order.Id })" data-type="open-modal">@order.Name</a></td>
                        <td>@order.Price</td>
                        <td>@($"{order.CreateDate:f}")</td>
                    </tr>
                }
            </tbody>
        </table>

        if (Model.Total > Model.ItemsPerPage)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item @(!Model.HasPrev ? "disabled" : "")">
                        <a data-ajax="true"
                           data-ajax-method="GET"
                           data-ajax-mode="replace"
                           data-ajax-update="#modal-body"
                           class="page-link"
                           href="@Url.Action("GridByReferenceId", null, new { id = Model.ParentId, page = Model.CurrentPage - 1})"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    @for (int i = 0; i < Model.PagesCount; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a data-ajax="true"
                               data-ajax-method="GET"
                               data-ajax-mode="replace"
                               data-ajax-update="#modal-body"
                               class="page-link"
                               href="@Url.Action("GridByReferenceId", null, new { id = Model.ParentId,  page = i})">@(i + 1)</a>
                        </li>
                    }

                    <li class="page-item @(!Model.HasNext ? "disabled" : "")">
                        <a data-ajax="true"
                           data-ajax-method="GET"
                           data-ajax-mode="replace"
                           data-ajax-update="#clients-grid-container"
                           class="page-link"
                           href="@Url.Action("Grid", null, new { page = Model.CurrentPage + 1})"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        }
    }
</div>